spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_payment_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Singapore
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: PAYMENT-SERVICE
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8100